version: '3'

services:
  db:
    user: $UID
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: node-auth
      MONGO_USERNAME: phantom
      MONGO_PASSWORD: mypassword
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  
  cache:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: ['--requirepass "mypassword"']